(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['size-guide'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return "<div class=\"container\">\n    <div class=\"guide__header\">\n        <div class=\"close-button close-button--guide\"></div>\n    </div>\n    <div class=\"guide-main__title\">\n\n    </div>\n    <div class=\"guide-section\">\n        <div class=\"guide__image\">\n\n            "
    + alias3((helpers.loadSVG || (depth0 && depth0.loadSVG) || alias2).call(alias1,1,{"name":"loadSVG","hash":{},"data":data}))
    + "\n        </div>\n        <div class=\"guide__content\">\n            <div class=\"guide__parts\">\n                <div class=\"guide__part\">1 - Foot length</div>\n            </div>\n            <h3 class=\"guide__title\">HOW TO MEASURE YOUR FOOT LENGTH?</h3>\n            <p class=\"guide__text\">\n                1. To measure your feet take a piece of paper down to the floor. You are going to trace an outline of your barefoot onto\n                this paper, so pick a hard surface that&#39;s easy to draw on.\n                <br>\n                <br> 2. Place your foot firmly on top of the piece of paper. Bend your leg slightly, with your shin in front\n                of your ankle.\n                <br>\n                <br> 3. Trace your foot. Draw the outline of your foot all the way around. Be precise.\n                <br>\n                <br> 4. Mark the length of your foot on the paper. Use your marker to draw straight line touching each side of\n                the outline.\n                <br>\n                <br> 5. Measure the length of your foot. Use a tape measure or ruler to measure from the big toe to heel of your\n                foot. This number determine your shoe size.\n                <br>\n                <br> One foot is often slightly larger than the other. For best results, follow these steps for both feet.\n        </div>\n    </div>\n    <div class=\"guide-section guide-section--inverse\">\n        <div class=\"guide__image\">\n            "
    + alias3((helpers.loadSVG || (depth0 && depth0.loadSVG) || alias2).call(alias1,2,{"name":"loadSVG","hash":{},"data":data}))
    + "\n        </div>\n        <div class=\"guide__content\">\n            <div class=\"guide__parts\">\n                <div class=\"guide__part\">2 - Ball circumference</div>\n                <div class=\"guide__part\">3 - Instep circumference</div>\n                <div class=\"guide__part\">4 - Heel girth</div>\n                <div class=\"guide__part\">5 - Ankle girth</div>\n            </div>\n            <h3 class=\"guide__title\">HOW TO MEASURE THE WIDTH OF YOUR FOOT ?</h3>\n            <p class=\"guide__text\">Your width fitting is just as important as your shoe size so after you finish with measuring your foot length,\n                you need to measure the width of your foot.\n                <br>Knowing your shoe width can make a world of difference when it comes to finding comfortable footwear.\n                <br> Many people need narrow or wide shoes, so this step is just as important as the last.\n            </p>\n        </div>\n    </div>\n    <div class=\"guide-section guide-section--extra\">\n        <div class=\"guide__image\">\n            "
    + alias3((helpers.loadSVG || (depth0 && depth0.loadSVG) || alias2).call(alias1,3,{"name":"loadSVG","hash":{},"data":data}))
    + "\n        </div>\n        <div class=\"guide__content\">\n            <div class=\"guide__parts\">\n                <div class=\"guide__part\">2 - Ball circumference</div>\n                <div class=\"guide__part\">3 - Instep circumference</div>\n                <div class=\"guide__part\">4 - Heel girth</div>\n                <div class=\"guide__part\">5 - Ankle girth</div>\n            </div>\n            <p class=\"guide__text\">\n                Proccedure is very simple. Use a tape measure and measure the spots of the marked places going around the foot.\n                <br> If you send us your own measurements, we will make sandals only for you as a custom order.\n                <br> It is very important to measure your feet as accurately as possible and get your DIOCLETIA`s in the right\n                size.\n            </p>\n\n        </div>\n    </div>\n</div>";
},"useData":true});
})();